export const enum CustomResponseType {
  OK = '6000',
  OK_MESSAGE = '成功',

  FORMAT_ERROR = '6101',
  FORMAT_ERROR_MESSAGE = '輸入格式錯誤：',

  FILE_TYPE_ERROR = '6102',
  FILE_TYPE_ERROR_MESSAGE = '檔案格式錯誤',

  IMAGE_TYPE_ERROR = '6103',
  IMAGE_TYPE_ERROR_MESSAGE = '圖片格式錯誤',

  PWD_CONFIRMPWD_NOT_THE_SAME = '6104',
  PWD_CONFIRMPWD_NOT_THE_SAME_MESSAGE = '密碼與確認密碼不同',

  UNREGISTERED_USER = '6201',
  UNREGISTERED_USER_MESSAGE = '尚未註冊，查詢不到此用戶',

  WRONG_PASSWORD = '6202',
  WRONG_PASSWORD_MESSAGE = '密碼錯誤',

  ACCOUNT_REGISTERED = '6203',
  ACCOUNT_REGISTERED_MESSAGE = '帳號已被註冊：',

  UNKNOWN_ERROR = '6204',
  UNKNOWN_ERROR_MESSAGE = '不明錯誤',

  EMAIL_VERIFICATION_FAILED = '6205',
  EMAIL_VERIFICATION_FAILED_MESSAGE = '忘記密碼信箱驗證失敗',

  CAN_NOT_USE_OLD_PASSWORD = '6206',
  CAN_NOT_USE_OLD_PASSWORD_MESSAGE = '不可使用舊密碼',

  NO_DATA_FOUND = '6207',
  NO_DATA_FOUND_MESSAGE = '查無資料',

  OLD_PASSWORD_INCORRECT = '6208',
  OLD_PASSWORD_INCORRECT_MESSAGE = '您的舊密碼不正確',

  SHARE_TICKET_FAILED = '6209',
  SHARE_TICKET_FAILED_MESSAGE = '分票失敗',

  WRITE_OFF_FAILED = '6210',
  WRITE_OFF_FAILED_MESSAGE = '票券核銷失敗',

  PAGINATION_INFO_MISSING = '6211',
  PAGINATION_INFO_MISSING_MESSAGE = '沒有給適當的分頁資訊',

  PRODUCT_NOT_FOUND = '6212',
  PRODUCT_NOT_FOUND_MESSAGE = '無此商品 ID',

  INSERT_ERROR = '6213',
  INSERT_ERROR_MESSAGE = '新增錯誤',

  UPDATE_ERROR = '6214',
  UPDATE_ERROR_MESSAGE = '更新錯誤',

  DELETE_ERROR = '6215',
  DELETE_ERROR_MESSAGE = '刪除錯誤',

  EMAIL_REGISTERED = '6216',
  EMAIL_REGISTERED_MESSAGE = '信箱已被註冊：',

  TOKEN_GENERATE_ERROR = '6301',
  TOKEN_GENERATE_ERROR_MESSAGE = 'token 建立失敗',

  TOKEN_EXPIRED = '6302',
  TOKEN_EXPIRED_MESSAGE = 'token 過期',

  PERMISSION_DENIED = '6401',
  PERMISSION_DENIED_MESSAGE = '不允許使用該方法',

  ACCOUNT_DISABLED = '6402',
  ACCOUNT_DISABLED_MESSAGE = '此帳號已停用',

  SYSTEM_ERROR = '6501',
  SYSTEM_ERROR_MESSAGE = '系統錯誤',

  IMAGE_UPLOAD_ERROR = '6502',
  IMAGE_UPLOAD_ERROR_MESSAGE = '上傳圖片失敗',

  PAYMENT_FAILED = '6503',
  PAYMENT_FAILED_MESSAGE = '付款失敗',
}
